#!/bin/bash
# Script: remove-old-kernels
# Author: Andrej Georgievski <andrej.zgeorgievski@gmail.com>
# Created: 28 Feb 2017
# Version: 1.0

# If the /boot partition is low on space and can't process kernel updates, 
# this script can free some /boot partition space by deleting old kernels.
# Idea: http://tuxtweaks.com/2010/10/remove-old-kernels-in-ubuntu-with-one-command/

echo "Removing old kernels and headers to free /boot drive space..."
echo "Packages to be deleted:"
dpkg -l linux-* | awk '/^ii/{ print $2}' | grep -v -e `uname -r | cut -f1,2 -d"-"` | grep -e [0-9] | grep -E "(image|headers)"
read -n1 -rsp $'Press any key to continue or Ctrl+C to exit...\n'

echo 
echo "Uninstalling old kernels..."
dpkg -l linux-* | awk '/^ii/{ print $2}' | grep -v -e `uname -r | cut -f1,2 -d"-"` | grep -e [0-9] | grep -E "(image|headers)" | xargs sudo apt-get -y purge
